### ISSUE TITLE
how can we test chunking is working? 

### ISSUE THREAD

**Issue by pooranravabe** [FineUploader/php-traditional-server#10]
when we upload a file with 1GB for example , how can we know or test chunking is working or not ? 

is it necessary to set chunking : true, to set endpoints

**Comment by rnicholus** [comment]
Easiest would be to look at network requests.

**Comment by pooranravabe** [comment]
ok. thanks ..... if i am uploading file size of more than chunk size ... it uploads file by "blob".. and with separate chunks.. how I get a single file as same  it before uploading
