### ISSUE TITLE
Uploading error 

### ISSUE THREAD

**Issue by bobyper** [FineUploader/php-traditional-server#11]
handler.php not check for $_FILES['qqfile']['error']
If error occurrence, FineUuploader continue with next chunk.

Something like this bellow, need near line # 138 in handler.php
        if($file['error']) {
            return array('error' => 'Upload Error #'.$file['error']);
        }

**Comment by rnicholus** [comment]
When will Fine Uploader send such a parameter with the request? I am not aware of one.

**Comment by bobyper** [comment]
PHP set erorr if file comes wrong. During upload if network drops some packet and file come to server wrong . Anyway, i have from time to time error =3  
(from PHP documentation:  UPLOAD_ERR_PARTIAL Value: 3; The uploaded file was only partially uploaded.)

**Comment by rnicholus** [comment]
Ah, I see. Can you open up a pull request with the proposed change? I will take a look, and it all looks well, I'll publish an updated version to composer/packagist.

**Comment by rnicholus** [comment]
Fixed in #12.
