### ISSUE TITLE
PHP 7.1 non well formed numeric value Notice

### ISSUE THREAD

**Issue by Punchlinern** [FineUploader/php-traditional-server#18]
When running FineUploader on PHP 7.1 I get the following Notice when I upload a file:
`Notice:  A non well formed numeric value encountered in UploadHandler.php on line 333`
The upload succeeds, but since the error messages are returned the JSON can't be parsed, and the  JS believe the upload failed.

**Comment by rnicholus** [comment]
Speak of the devil! Does #17 solve the issue for you?

**Comment by Punchlinern** [comment]
Oh, I hadn't seen that! It sure does. Great!

**Comment by rnicholus** [comment]
If you are able to confirm via manual testing that this solves the issue for you, I'll go ahead and merge that change in and push a new version to packagist/composer.

**Comment by Punchlinern** [comment]
It does solve the issue for me. I tried it on a server where I had the uploader working on PHP 7.0. Switched to 7.1 and got the notice. When I pasted the code from #17 it started working.

**Comment by rnicholus** [comment]
Great, thanks for the confirmation.

**Comment by rnicholus** [comment]
Fix merged and released as [v1.2.2](https://github.com/FineUploader/php-traditional-server/releases/tag/1.2.2).

**Comment by Mashiekane** [comment]
hy guys Im also coming across above error and im new in php please help.Below are my errors and qoutes.

Notice: A non well formed numeric value encountered in D:\xampp\htdocs\1\convert.php on line 16

Notice: A non well formed numeric value encountered in D:\xampp\htdocs\1\convert.php on line 16

Notice: A non well formed numeric value encountered in D:\xampp\htdocs\1\convert.php on line 19

Notice: A non well formed numeric value encountered in D:\xampp\htdocs\1\convert.php on line 19

<?php
$rand=rand("100", "500");
$src="image.jpg";
$dest="thumb/$rand.png";
$desired_width="500px";
$desired_height="294px";

function create_thumb($src, $dest, $desired_width,$desired_height) {
/* read the original image */
$source_image = imagecreatefromjpeg($src);
$width = imagesx($source_image);
$height = imagesy($source_image);
/* find the “desired height” of this thumbnail, relative to the desired width */
 $desired_height = floor($height * ($desired_width / $width));
/* we will create a temporary image */
                                      line 16 $virtual_image = imagecreatetruecolor($desired_width, $desired_height);
/* copy source image at a re-sized size */
imagecopyresampled($virtual_image, $source_image, 0, 0, 0, 0,
                line 19             $desired_width, $desired_height, $width, $height);
/* create and save the thumbnail image to its destination */
imagegif($virtual_image, $dest);
}

create_thumb($src, $dest, $desired_width,$desired_height);

?>
