### ISSUE TITLE
XHR returned response code 0

### ISSUE THREAD

**Issue by asadadams** [FineUploader/php-traditional-server#30]
Always receiving an XHR returned response code 0 when uploading specific files on the server

**Comment by rnicholus** [comment]
that isn't related to the code here - caused by a network or server issue

**Comment by VersatilityWerks** [comment]
Kinda does because I think the real issue is XHR timeout. How can we set the timeout period for the call? My server creates thumbnails and stuff so it takes a bit on large files.
