### ISSUE TITLE
File Name Empty

### ISSUE THREAD

**Issue by kishkool** [FineUploader/php-traditional-server#5]
Hi,

I've downloaded your demo client version from your website, the one with "start upload" and i've downloaded the php-traditional-server version for server side.
I was able to upload easily a photo, but when i try to upload a video (80MB) i've got this error : 
[Fine Uploader 5.3.2] Received response status 200 with body: {"error":"File name empty.","uploadName":null}
I don't konw why it happens.

Thanks for your help

**Comment by kishkool** [comment]
Please forget, it was the post max size in my php.ini.
Do you have any example with speed on UI? or ETA?

**Comment by rnicholus** [comment]
See FineUploader/fine-uploader#1460.

**Comment by mattogodoy** [comment]
I'm having the same empty name problem. I already increased the _post_max_size_ and _upload_max_filesize_ variables and the changes are correctly displayed using _phpInfo_, but the problem persists.
If the file is small, I get "responseJSON.uploadName". If the file is big, it gets uploaded correctly to the server, but "responseJSON" only contains the "uuid" parameter, but no name.

Any ideas?
